name: Sync Subfolder to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push Back-End Subfolder to Hugging Face
      run: |
        cd Back-End
        
        git init -b main
        git config user.name "GitHub Action"
        git config user.email "actions@github.com"
        
        git add .
        git commit -m "Deploy Backend from Monorepo"
        
        git push --force https://AyusufAR:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/AyusufAR/liveup main